# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [4]:

import pandas as pd 
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [5]:
# a = 

a = pd.Series([100,200,300,400])

Print a, and data type

In [6]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [7]:
import pandas._libs.indexing
from numpy import e
a[2]

np.int64(300)

What are the values of index for series a?

In [8]:

a.values

array([100, 200, 300, 400])

Change the index to  ['c', 'a', 'b', 'd']

In [9]:
a.index = ['c','a','b','d']

Access the value in the series with index 'd'

In [10]:

a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [11]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [12]:
# b = 

b = pd.Series([800,450,100])
b.index = ["e","f","g"]
b

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [13]:
# a =

a = pd.concat([a,b])

In [14]:
#print a again after appending b into it

a

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [15]:
# a = 
asort = a.sort_values(ascending=True)

In [16]:
asort

c    100
g    100
a    200
b    300
d    400
f    450
e    800
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [17]:
# df = 
df = pd.DataFrame(a)

In [18]:
df

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [19]:
df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [20]:
# yep its same as the series.

df.index

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [21]:
df.head()

# It will show first 5 rows of the data

     0
c  100
a  200
b  300
d  400
e  800

In [22]:
df.tail()

# it will show last 5 rows

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [23]:
df.columns= ['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [24]:
#Create fruits array

# fruits =

fruits = ['orange', 'mango', 'apple']
fruits_array = np.random.choice(fruits, size=7)
print(fruits_array)

['mango' 'orange' 'mango' 'orange' 'orange' 'orange' 'mango']

In [25]:
#Create series fruits out of fruits array
fruits = pd.Series(fruits_array)
fruits

0     mango
1    orange
2     mango
3    orange
4    orange
5    orange
6     mango
dtype: object

Change the index of fruits to the index of dataframe df

In [26]:


fruits.index = df.index
fruits

c     mango
a    orange
b     mango
d    orange
e    orange
f    orange
g     mango
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [27]:
df["fruits"] = fruits

print(df)

   points  fruits
c     100   mango
a     200  orange
b     300   mango
d     400  orange
e     800  orange
f     450  orange
g     100   mango

In [28]:

df.head()

   points  fruits
c     100   mango
a     200  orange
b     300   mango
d     400  orange
e     800  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [29]:
# d1 = 
d1 = pd.DataFrame({
    "city" : ["Chandigarh", "Delhi", "Kanpur", "Chennai", "Manali" ],
    "Temperature" : [15, 22, 20, 26,-2]
})

Print(d1)

In [30]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [31]:
d1.shape

(5, 2)

Set city = d1['city']

In [32]:

city = d1['city']
city

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

print city <br>
What is the type of city.

In [33]:

print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [34]:
# d2 = 

d2 = pd.DataFrame({
    "city":["Bengaluru", "Coimbatore", "Srirangam", "Pondicherry"],
    "Temperature":[24,35,36,39]
})

print the shape of this dataframe

In [35]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [36]:
# d3 = 
d3 = pd.concat([d1,d2], ignore_index=True)
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengaluru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [37]:

lesstemp20 = d3[d3['Temperature'] <= 20]
display(lesstemp20)
print(f"Number of cities with temp <= 20: {len(lesstemp20)}")

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Number of cities with temp <= 20: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [38]:
greaterthen30 = d3[d3['Temperature'] >= 30]
greaterthen30

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [39]:
# write function here

# def is_ut(x):
    
#     # write code below
    
# d3['is_ut'] = 

def is_ut(city):
    ut_city = ["Chandigarh","Pondicherry","Delhi"]
    return city in ut_city

d3['is_ut'] = d3['city'].apply(is_ut)

d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengaluru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

In [40]:
# print d3

print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengaluru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [41]:
# write function here

def c_to_f(c):
    return (c * 9/5) + 32

In [42]:
# check function c_to_f(10)
print(f"Test: c_to_f(10) = {c_to_f(10)}")

Test: c_to_f(10) = 50.0

In [43]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
display(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
5    Bengaluru           24  False            75.2
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [56]:
subset_ut = d1[d1['city'].isin(['Chandigarh', 'Delhi'])]

subset_ut

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [57]:

subset_hot = d1[d1['Temperature'] > 90]
subset_hot

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [ ]:
first_three_rows = d1.head(3)
print(first_three_rows)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [59]:
# select all the rows and last two columns in the dataframe. 
subset_last_two_cols = d1.iloc[:, -2:]

subset_last_two_cols

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26

## Groupby

In [61]:
# Create a dataframe using dictionary of your choice

# data = 
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "City": ["New York", "Los Angeles", "Chicago", "Houston"]
}

In [62]:
# Use Groupby of single column with aggregate sum()

data_df = pd.DataFrame(data)
data_df.groupby('City').sum()

                Name  Age
City
Chicago      Charlie   35
Houston        David   40
Los Angeles      Bob   30
New York       Alice   25

In [63]:
# Use Groupby of single column with aggregate count()
data_df.groupby('City').count()

             Name  Age
City
Chicago         1    1
Houston         1    1
Los Angeles     1    1
New York        1    1

In [68]:
# Use Groupby of single column with aggregate min() and max()

data_df.groupby('City').min()

                Name  Age
City
Chicago      Charlie   35
Houston        David   40
Los Angeles      Bob   30
New York       Alice   25

In [69]:
data_df.groupby('City').max()

                Name  Age
City
Chicago      Charlie   35
Houston        David   40
Los Angeles      Bob   30
New York       Alice   25

In [65]:
# Use Groupby of any 2 columns with aggregate mean()
data_df.groupby(['City', 'Name']).mean()

                      Age
City        Name
Chicago     Charlie  35.0
Houston     David    40.0
Los Angeles Bob      30.0
New York    Alice    25.0

In [66]:
# Use Groupby of any 2 columns with aggregate min() and max()

data_df.groupby(['City', 'Name']).min()

                     Age
City        Name
Chicago     Charlie   35
Houston     David     40
Los Angeles Bob       30
New York    Alice     25

In [67]:
data_df.groupby(['City', 'Name']).max()

                     Age
City        Name
Chicago     Charlie   35
Houston     David     40
Los Angeles Bob       30
New York    Alice     25

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [72]:
# a = 
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [73]:

a

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [74]:

len(a)

457

What is the type of a?

In [75]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex